# Importing Libraries

In [43]:
import pandas as pd
import numpy as np
import nltk
import re
from  nltk.corpus import stopwords
from  nltk.stem import WordNetLemmatizer
import string

In [45]:
df_fake = pd.read_csv("Fake.csv")
df_true = pd.read_csv("True.csv")

In [46]:
df_fake["label"] = 0
df_true["label"] = 1

In [47]:
df_fake

title  \
0       Donald Trump Sends Out Embarrassing New Year’...   
1       Drunk Bragging Trump Staffer Started Russian ...   
2       Sheriff David Clarke Becomes An Internet Joke...   
3       Trump Is So Obsessed He Even Has Obama’s Name...   
4       Pope Francis Just Called Out Donald Trump Dur...   
...                                                  ...   
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   

                                                    text      subject  \
0      Donald Trump just couldn t wish all Americans ...         News   
1      House Intelligence Committee Chairman Devin Nu...         News   
2      On Friday, it was revealed that former Milwauk...         News   
3      On Christmas day, Donald Trump announced that ...         News   
4      Pope Francis used his annual Christmas Day mes...         News   
...                                                  ...          ...   
23476  21st Century Wire says As 21WIRE reported earl...  Middle-east   
23477  21st Century Wire says It s a familiar theme. ...  Middle-east   
23478  Patrick Henningsen  21st Century WireRemember ...  Middle-east   
23479  21st Century Wire says Al Jazeera America will...  Middle-east   
23480  21st Century Wire says As 21WIRE predicted in ...  Middle-east   

                    date  label  
0      December 31, 2017      0  
1      December 31, 2017      0  
2      December 30, 2017      0  
3      December 29, 2017      0  
4      December 25, 2017      0  
...                  ...    ...  
23476   January 16, 2016      0  
23477   January 16, 2016      0  
23478   January 15, 2016      0  
23479   January 14, 2016      0  
23480   January 12, 2016      0  

[23481 rows x 5 columns]

In [48]:
dataset1=df_fake[['text','label']]
dataset2=df_true[['text','label']]

In [49]:
dataset1

text  label
0      Donald Trump just couldn t wish all Americans ...      0
1      House Intelligence Committee Chairman Devin Nu...      0
2      On Friday, it was revealed that former Milwauk...      0
3      On Christmas day, Donald Trump announced that ...      0
4      Pope Francis used his annual Christmas Day mes...      0
...                                                  ...    ...
23476  21st Century Wire says As 21WIRE reported earl...      0
23477  21st Century Wire says It s a familiar theme. ...      0
23478  Patrick Henningsen  21st Century WireRemember ...      0
23479  21st Century Wire says Al Jazeera America will...      0
23480  21st Century Wire says As 21WIRE predicted in ...      0

[23481 rows x 2 columns]

In [50]:
dataset2

text  label
0      WASHINGTON (Reuters) - The head of a conservat...      1
1      WASHINGTON (Reuters) - Transgender people will...      1
2      WASHINGTON (Reuters) - The special counsel inv...      1
3      WASHINGTON (Reuters) - Trump campaign adviser ...      1
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      1
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      1
21413  LONDON (Reuters) - LexisNexis, a provider of l...      1
21414  MINSK (Reuters) - In the shadow of disused Sov...      1
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      1
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      1

[21417 rows x 2 columns]

In [51]:
dataset=pd.concat([dataset1,dataset2])

In [52]:
dataset

text  label
0      Donald Trump just couldn t wish all Americans ...      0
1      House Intelligence Committee Chairman Devin Nu...      0
2      On Friday, it was revealed that former Milwauk...      0
3      On Christmas day, Donald Trump announced that ...      0
4      Pope Francis used his annual Christmas Day mes...      0
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      1
21413  LONDON (Reuters) - LexisNexis, a provider of l...      1
21414  MINSK (Reuters) - In the shadow of disused Sov...      1
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      1
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      1

[44898 rows x 2 columns]

In [55]:
dataset.shape

(44898, 2)

In [63]:
dataset.isnull().sum()

text     0
label    0
dtype: int64

In [65]:
dataset['label'].value_counts()

label
0    23481
1    21417
Name: count, dtype: int64

In [67]:
dataset=dataset.sample(frac = 1)

In [69]:
dataset

text  label
5204   Sarah Palin is a proud Trump supporter, but yo...      0
3231   The liberal billionaire donor just called out ...      0
14455  If you look closely, you might find a few fami...      0
6825   WASHINGTON (Reuters) - The U.S. Senate overwhe...      1
17038  ATHENS (Reuters) - A potential deal with the U...      1
...                                                  ...    ...
20976  Just when you think you ve heard everything th...      0
8543   Supporters of Senator Bernie Sanders can now c...      0
7529   STERLING HEIGHTS, Mich. (Reuters) - Republican...      1
16582  BEIJING (Reuters) - China s ruling Communist P...      1
7211   Republican presidential frontrunner Donald Tru...      0

[44898 rows x 2 columns]

In [71]:
ps=WordNetLemmatizer()

In [73]:
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\pslpa\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pslpa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [75]:
stopwords=stopwords.words('english')

In [77]:
def clean_row(row):
    row=row.lower()
    row = re.sub(' [^a-zA-Z]', ' ', row)
    token = row.split()
    news = [ps.lemmatize(word) for word in token if not word in stopwords]
    cleanned_news = ' '.join(news)
    return cleanned_news

In [79]:
dataset['text']

5204     Sarah Palin is a proud Trump supporter, but yo...
3231     The liberal billionaire donor just called out ...
14455    If you look closely, you might find a few fami...
6825     WASHINGTON (Reuters) - The U.S. Senate overwhe...
17038    ATHENS (Reuters) - A potential deal with the U...
                               ...                        
20976    Just when you think you ve heard everything th...
8543     Supporters of Senator Bernie Sanders can now c...
7529     STERLING HEIGHTS, Mich. (Reuters) - Republican...
16582    BEIJING (Reuters) - China s ruling Communist P...
7211     Republican presidential frontrunner Donald Tru...
Name: text, Length: 44898, dtype: object

In [81]:
dataset['text'] = dataset['text']. apply (lambda x : clean_row(x))

In [82]:
dataset['text']

5204     sarah palin proud trump supporter, know t? fat...
3231     liberal billionaire donor called donald trump ...
14455    look closely, might find familiar hypocrite ca...
6825     washington reuters) u.s. senate overwhelmingly...
17038    athens reuters) potential deal united state up...
                               ...                        
20976    think heard everything great respite deserving...
8543     supporter senator bernie sander cool pint ice ...
7529     sterling heights, mich. reuters) republican pr...
16582    beijing reuters) china ruling communist party ...
7211     republican presidential frontrunner donald tru...
Name: text, Length: 44898, dtype: object

In [83]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [161]:
vectorizer=TfidfVectorizer(max_features=1000,lowercase=False,ngram_range=(1,2))

In [163]:
x=dataset.iloc[:35000,0]
y=dataset.iloc[:35000,1]

In [164]:
x

5204     sarah palin proud trump supporter, know t? fat...
3231     liberal billionaire donor called donald trump ...
14455    look closely, might find familiar hypocrite ca...
6825     washington reuters) u.s. senate overwhelmingly...
17038    athens reuters) potential deal united state up...
                               ...                        
11937    helsinki reuters) senior politician finland eu...
10159    washington reuters) u.s. republican presidenti...
22641    21st century wire say mitt romney make incredi...
19848    peshawar, pakistan reuters) militant pakistani...
4219     trump mouthpiece jeffrey lord got a** handed a...
Name: text, Length: 35000, dtype: object

In [167]:
y

5204     0
3231     0
14455    0
6825     1
17038    1
        ..
11937    1
10159    1
22641    0
19848    1
4219     0
Name: label, Length: 35000, dtype: int64

In [169]:
from sklearn.model_selection import train_test_split

In [171]:
train_data, test_data,train_label, test_label = train_test_split(x, y, test_size=0.2,random_state=0)

In [173]:
vec_train_data = vectorizer.fit_transform(train_data)

In [174]:
vec_train_data = vec_train_data.astype('float32').toarray()

In [177]:
vec_test_data = vectorizer.fit_transform(test_data)

In [178]:
vec_test_data = vec_test_data.toarray()

In [179]:
vec_test_data.shape,vec_train_data.shape

((7000, 1000), (28000, 1000))

In [180]:
vec_train_data

array([[0.        , 0.        , 0.        , ..., 0.02661197, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.06464866, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.03799149, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.05453643, 0.        ,
        0.        ]], dtype=float32)

In [181]:
vec_test_data

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.06677022, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [182]:
train_data = pd.DataFrame(vec_train_data, columns=vectorizer.get_feature_names_out())
testing_data = pd.DataFrame(vec_test_data, columns=vectorizer.get_feature_names_out())

In [183]:
train_data

00       000       012       013  014       015       016  \
0      0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000   
1      0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.041771   
2      0.000000  0.000000  0.064649  0.000000  0.0  0.056082  0.000000   
3      0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000   
4      0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000   
...         ...       ...       ...       ...  ...       ...       ...   
27995  0.190737  0.084919  0.000000  0.000000  0.0  0.000000  0.000000   
27996  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000   
27997  0.000000  0.037991  0.000000  0.053682  0.0  0.000000  0.000000   
27998  0.000000  0.000000  0.000000  0.060642  0.0  0.052095  0.000000   
27999  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.051836   

            017      able  abortion  ...     wrong     wrote  year  year old  \
0      0.096246  0.000000       0.0  ...  0.028992  0.034304   0.0  0.016622   
1      0.000000  0.000000       0.0  ...  0.119694  0.000000   0.0  0.000000   
2      0.000000  0.056033       0.0  ...  0.189164  0.000000   0.0  0.061974   
3      0.000000  0.074204       0.0  ...  0.000000  0.000000   0.0  0.041036   
4      0.000000  0.000000       0.0  ...  0.068212  0.000000   0.0  0.000000   
...         ...       ...       ...  ...       ...       ...   ...       ...   
27995  0.000000  0.000000       0.0  ...  0.000000  0.000000   0.0  0.000000   
27996  0.000000  0.000000       0.0  ...  0.000000  0.000000   0.0  0.000000   
27997  0.000000  0.000000       0.0  ...  0.044443  0.000000   0.0  0.000000   
27998  0.000000  0.000000       0.0  ...  0.000000  0.000000   0.0  0.086353   
27999  0.000000  0.000000       0.0  ...  0.029707  0.000000   0.0  0.374709   

          years  yes       yet      york  you  young  
0      0.029908  0.0  0.000000  0.026612  0.0    0.0  
1      0.000000  0.0  0.000000  0.000000  0.0    0.0  
2      0.000000  0.0  0.000000  0.000000  0.0    0.0  
3      0.000000  0.0  0.000000  0.000000  0.0    0.0  
4      0.000000  0.0  0.000000  0.000000  0.0    0.0  
...         ...  ...       ...       ...  ...    ...  
27995  0.000000  0.0  0.000000  0.000000  0.0    0.0  
27996  0.000000  0.0  0.000000  0.000000  0.0    0.0  
27997  0.000000  0.0  0.000000  0.000000  0.0    0.0  
27998  0.000000  0.0  0.000000  0.000000  0.0    0.0  
27999  0.000000  0.0  0.056505  0.054536  0.0    0.0  

[28000 rows x 1000 columns]

In [184]:
from sklearn.naive_bayes import MultinomialNB

In [185]:
clf=MultinomialNB()

In [186]:
clf.fit(train_data,train_label)

MultinomialNB()

In [187]:
y_pred=clf.predict(testing_data)

In [201]:
test_label

12125    1
12303    1
3789     0
188      1
6653     0
        ..
9996     1
11096    0
21161    0
11711    0
18870    1
Name: label, Length: 7000, dtype: int64

In [199]:
y_pred

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [205]:
from sklearn.metrics import accuracy_score

In [209]:
accuracy_score(test_label,y_pred)

0.6368571428571429

# testing

In [214]:
txt='The following statements were posted to the verified Twitter accounts of U.S. President Donald Trump, @realDonaldTrump and @POTUS.  The opinions expressed are his own. Reuters has not edited the statements or confirmed their accuracy.  @realDonaldTrump : - Vanity Fair, which looks like it is on its last legs, is bending over backwards in apologizing for the minor hit they took at Crooked H. Anna Wintour, who was all set to be Amb to Court of St James’s & a big fundraiser for CH, is beside herself in grief & begging for forgiveness! [1024 EST] -- Source link: (bit.ly/2jBh4LU) (bit.ly/2jpEXYR) '

In [220]:
news=clean_row(txt)

In [222]:
news

'following statementsâ posted verified twitter account u.s. president donald trump, realdonaldtrump potus. opinion expressed own.â reuters edited statement confirmed accuracy. @realdonaldtrump vanity fair, look like last legs, bending backwards apologizing minor hit took crooked h. anna wintour, set amb court st james’s big fundraiser ch, beside grief begging forgiveness! 1024 est] - source link: bit.ly/2jbh4lu) bit.ly/2jpexyr)'

In [226]:
pred = clf. predict (vectorizer. transform([news]) . toarray( ))

C:\Users\pslpa\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


In [228]:
pred

array([0], dtype=int64)

In [238]:
if pred == 0:
    print('News is correct')
else:
    print ("News is Fake")

News is correct


In [242]:
txt = input ("Enter News") 
ews = clean_row(str(txt))
if pred == 0:
    print('News is correct')
else:
    print ("News is Fake")

Enter News following statementsâ posted verified twitter account u.s. president donald trump, realdonaldtrump potus. opinion expressed own.â reuters edited statement confirmed accuracy. @realdonaldtrump vanity fair, look like last legs, bending backwards apologizing minor hit took crooked h. anna wintour, set amb court st james’s big fundraiser ch, beside grief begging forgiveness! 1024 est] - source link: bit.ly/2jbh4lu) bit.ly/2jpexyr)


News is correct
